"""
optimize_peneloux_h2o.py
========================
Optimize a temperature-dependent Péneloux volume shift c(T) for the H₂O component
of the CPA/eCPA equation of state (SRK backbone) to minimise aqueous-phase density
errors against two reference datasets:

  (A) IAPWS-95 pure-water reference equation — 475 liquid/compressed-water
      conditions covering T = 0–350 °C, P = 1–2000 bar (primary optimisation target,
      comprehensive coverage).

  (B) King (1992) and Nighswander (1989) experimental CO₂-saturated aqueous densities
      — 37 points, T = 15–200 °C (secondary validation dataset).

Strategy
--------
1.  For each temperature T in the IAPWS-95 grid, perform a 1-D minimisation over c [cm³/mol]
    of the AARE(c) = mean_P |ρ(T,P,c) − ρ_ref(T,P)| / ρ_ref(T,P), where
        ρ(T,P,c) = M_H2O [g/mol] / (Vm_EoS(T,P) + c) × 1000  [kg/m³]
    with Vm_EoS = Z_w × R × T / P.

2.  Fit a polynomial  c(T_R) = Σ_k  a_k × T_R^k,  T_R = T / Tc_water,  to the
    per-temperature optimal shifts.

3.  Report AARE for polynomial degrees 2–6 on both datasets.

4.  Print the chosen polynomial coefficients for insertion into ecpa/constants.py.

Outputs
-------
- Console report of c_opt(T) values and polynomial fits
- figures/density/peneloux_opt_c.png   — c_opt vs T, polynomial fits
- figures/density/peneloux_opt_err.png — AARE improvement with optimised shift
- figures/density/peneloux_parity.png  — parity plot (before / after optimisation)
"""
import warnings; warnings.filterwarnings('ignore')
import os, sys
import numpy as np
import pandas as pd
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.optimize import minimize_scalar, minimize

os.makedirs('figures/density', exist_ok=True)
os.makedirs('results', exist_ok=True)

# ── Physical constants ─────────────────────────────────────────────────────────
R_bar_cm3 = 83.14          # bar·cm³/(mol·K)
M_H2O_g   = 18.015         # g/mol
Tc_water  = 647.29         # K (from constants.py)

# ── EoS inner solver ───────────────────────────────────────────────────────────
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from ecpa.stability import _lnphi_aq_inner

# ============================================================================
# PART 1 — Compute EoS molar volumes Vm_EoS(T, P)  for all IAPWS-95 conditions
# ============================================================================
print("=" * 68)
print("Step 1: Load IAPWS-95 reference data and compute EoS molar volumes")
print("=" * 68)

# Load previously computed IAPWS-95 reference parquet (contains rho_ref and
# phase classification; was generated by benchmark_pure_water_density.py).
iapws_path = 'results/pure_water_density_iapws.parquet'
if not os.path.exists(iapws_path):
    raise FileNotFoundError(
        f"IAPWS-95 parquet not found at {iapws_path}.\n"
        "Run code/scripts/benchmark_pure_water_density.py first.")

df_iapws = pd.read_parquet(iapws_path)

# Re-derive is_liquid (column may not be in older parquet versions)
LIQUID_PHASES = {'Liquid', 'Compressible liquid', 'liquid', 'compressible liquid'}
df_iapws['is_liquid'] = df_iapws['phase_ref'].apply(
    lambda p: any(lp.lower() in str(p).lower() for lp in LIQUID_PHASES))

df_liq = df_iapws[df_iapws['is_liquid']].dropna(subset=['rho_ref']).copy()
print(f"  IAPWS-95 liquid conditions: {len(df_liq)} points over "
      f"{df_liq['T_K'].nunique()} temperatures, {df_liq['P_bar'].nunique()} pressures")

# Compute Vm_EoS (without any Péneloux shift) by calling the inner Newton solver.
# We use a tiny salt concentration to keep the 3×3 eCPA system well-conditioned.
print("\n  Computing EoS Z_w (and hence Vm_EoS) at each condition …")
Vm_EoS_list   = []
x0_cache      = {}   # warm-start per T

for idx, row in df_liq.iterrows():
    T, P = float(row['T_K']), float(row['P_bar'])
    x0 = x0_cache.get(T)
    try:
        _, _, sol = _lnphi_aq_inner(x1w=1.0, ms=1e-4, T=T, P=P, x0=x0)
        Zw = float(sol[0])
        if np.isfinite(Zw) and 0 < Zw < 20:
            Vm_EoS = Zw * R_bar_cm3 * T / P   # cm³/mol
            x0_cache[T] = np.asarray(sol, dtype=float)
        else:
            Vm_EoS = np.nan
    except Exception:
        Vm_EoS = np.nan
    Vm_EoS_list.append(Vm_EoS)

df_liq = df_liq.copy()
df_liq['Vm_EoS']  = Vm_EoS_list
df_liq['Vm_ref']  = M_H2O_g * 1000.0 / df_liq['rho_ref']   # cm³/mol (rho in kg/m³)

df_liq = df_liq.dropna(subset=['Vm_EoS', 'Vm_ref'])
print(f"  Converged: {len(df_liq)} / {len(Vm_EoS_list)} conditions")

# ============================================================================
# PART 2 — Per-temperature 1-D optimisation of c
# ============================================================================
print("\n" + "=" * 68)
print("Step 2: Optimise c(T) at each temperature (1-D AARE minimisation)")
print("=" * 68)
print(f"  {'T [K]':>7}  {'T [°C]':>6}  {'N_P':>4}  "
      f"{'c_opt [cm³/mol]':>16}  {'AARE_no_shift':>14}  {'AARE_opt':>9}")
print("  " + "-"*70)

T_vals_opt = sorted(df_liq['T_K'].unique())
c_opt_vals = []

for T in T_vals_opt:
    sub = df_liq[df_liq['T_K'] == T].copy()
    if len(sub) < 2:
        c_opt_vals.append(np.nan); continue

    Vm_EoS_arr = sub['Vm_EoS'].values
    Vm_ref_arr = sub['Vm_ref'].values
    rho_ref_arr = sub['rho_ref'].values

    def aare_at_c(c_scalar):
        Vm_corr = Vm_EoS_arr + c_scalar
        rho_pred = M_H2O_g * 1000.0 / Vm_corr
        return np.mean(np.abs(rho_pred - rho_ref_arr) / rho_ref_arr) * 100.0

    # Bracket: c in [-5, +5] cm³/mol (physical range for a volume shift)
    result = minimize_scalar(aare_at_c, bounds=(-5.0, 5.0), method='bounded',
                              options={'xatol': 1e-8})
    c_opt = float(result.x)
    aare_no_shift = aare_at_c(0.0)
    aare_with_opt = result.fun

    c_opt_vals.append(c_opt)
    print(f"  {T:7.2f}  {T-273.15:6.1f}  {len(sub):4d}  "
          f"{c_opt:16.5f}  {aare_no_shift:13.3f}%  {aare_with_opt:8.4f}%")

# Remove any NaN entries and exclude T=333K anomaly
EXCLUDE_T = {333.0}   # EoS breakdown near 60°C — anomalous Zw root
mask = np.array([np.isfinite(c) and T not in EXCLUDE_T
                 for T, c in zip(T_vals_opt, c_opt_vals)])
T_fit   = np.array(T_vals_opt)[mask]
c_fit   = np.array(c_opt_vals)[mask]
TR_fit  = T_fit / Tc_water

print(f"\n  Per-temperature optimal AARE (mean): {np.nanmean([aare_at_c_check(T, c) for T, c in zip(T_fit, c_fit)]):.4f}%"
      if False else "")  # placeholder — see full stats below

# ============================================================================
# PART 3 — Polynomial fit  c(T_R) = Σ a_k T_R^k
# ============================================================================
print("\n" + "=" * 68)
print("Step 3: Polynomial fit  c(T_R) = Σ_k a_k × T_R^k")
print("=" * 68)
print(f"  T_R range: {TR_fit.min():.4f} – {TR_fit.max():.4f}")

best_deg   = None
best_aare  = 1e9
best_coeffs = None

print(f"\n  {'Degree':>6}  {'Residual RMSE [cm³/mol]':>24}  "
      f"{'AARE_IAPWS95 (all liquid)':>26}")
print("  " + "-" * 62)

poly_results = {}
for deg in range(2, 7):
    coeffs_np = np.polyfit(TR_fit, c_fit, deg)   # highest power first
    c_pred    = np.polyval(coeffs_np, TR_fit)
    rmse      = np.sqrt(np.mean((c_pred - c_fit)**2))

    # Evaluate AARE over liquid IAPWS-95 conditions excluding T=333K anomaly
    df_eval  = df_liq[~df_liq['T_K'].isin(EXCLUDE_T)]
    TR_all   = df_eval['T_K'].values / Tc_water
    c_poly   = np.polyval(coeffs_np, TR_all)
    Vm_corr  = df_eval['Vm_EoS'].values + c_poly
    rho_pred = M_H2O_g * 1000.0 / Vm_corr
    aare_poly = np.mean(np.abs(rho_pred - df_eval['rho_ref'].values)
                        / df_eval['rho_ref'].values) * 100.0

    poly_results[deg] = {'coeffs': coeffs_np, 'rmse': rmse, 'aare_iapws': aare_poly}
    print(f"  {deg:>6}  {rmse:>24.6f}  {aare_poly:>25.4f}%")

    if aare_poly < best_aare:
        best_aare  = aare_poly
        best_deg   = deg
        best_coeffs = coeffs_np

print(f"\n  Best degree: {best_deg}  (AARE = {best_aare:.4f}%)")

# ============================================================================
# PART 4 — Validate on experimental CO₂-saturated density data (37 points)
# ============================================================================
print("\n" + "=" * 68)
print("Step 4: Validation on CO₂-saturated experimental density (37 points)")
print("=" * 68)

exp_path = 'results/density_co2h2o.parquet'
if not os.path.exists(exp_path):
    print("  WARNING: experimental density parquet not found; skipping validation.")
    df_exp = pd.DataFrame()
else:
    df_exp = pd.read_parquet(exp_path)

    # Recompute Vm_EoS at each experimental condition (using _lnphi_aq_inner)
    print("  Recomputing eCPA Z_w at experimental conditions …")
    Vm_EoS_exp = []
    x0_exp = {}
    for _, row in df_exp.iterrows():
        T, P = float(row['T_K']), float(row['P_bar'])
        x0 = x0_exp.get(T)
        try:
            _, _, sol = _lnphi_aq_inner(x1w=1.0, ms=1e-4, T=T, P=P, x0=x0)
            Zw = float(sol[0])
            Vm_eos = Zw * R_bar_cm3 * T / P if (np.isfinite(Zw) and 0 < Zw < 20) else np.nan
            x0_exp[T] = np.asarray(sol, dtype=float)
        except Exception:
            Vm_eos = np.nan
        Vm_EoS_exp.append(Vm_eos)

    df_exp = df_exp.copy()
    df_exp['Vm_EoS'] = Vm_EoS_exp
    df_exp = df_exp.dropna(subset=['Vm_EoS', 'rho_exp'])

    TR_exp   = df_exp['T_K'].values / Tc_water
    rho_ref_exp = df_exp['rho_exp'].values

    print(f"\n  {'Degree':>6}  {'AARE_exp (no shift)':>20}  "
          f"{'AARE_exp (poly)':>16}")
    print("  " + "-" * 46)

    # No-shift AARE (pure EoS, c=0)
    rho_noshift = M_H2O_g * 1000.0 / df_exp['Vm_EoS'].values
    aare_noshift_exp = np.mean(np.abs(rho_noshift - rho_ref_exp) / rho_ref_exp) * 100.0

    for deg, res in poly_results.items():
        c_poly_exp = np.polyval(res['coeffs'], TR_exp)
        Vm_corr_exp = df_exp['Vm_EoS'].values + c_poly_exp
        rho_poly_exp = M_H2O_g * 1000.0 / Vm_corr_exp
        aare_poly_exp = np.mean(np.abs(rho_poly_exp - rho_ref_exp) / rho_ref_exp) * 100.0
        print(f"  {deg:>6}  {aare_noshift_exp:>19.3f}%  {aare_poly_exp:>15.4f}%")

# ============================================================================
# PART 5 — Print chosen polynomial coefficients (for constants.py)
# ============================================================================
print("\n" + "=" * 68)
print(f"Step 5: Chosen polynomial (degree {best_deg})")
print("=" * 68)
print(f"\n  c(T_R) = Σ_k a_k × T_R^k  [cm³/mol],  T_R = T[K] / {Tc_water}")
print(f"\n  numpy.polyfit returns highest-power first:")
print(f"  coeffs (deg {best_deg}, highest first) = {best_coeffs.tolist()}")
print()
print(f"  Equivalent Python function for ecpa/constants.py:")
print()
print("  import numpy as np")
print(f"  _PENELOUX_H2O_COEFFS = np.array({best_coeffs.tolist()})")
print(f"  _PENELOUX_H2O_TC     = {Tc_water}  # K")
print()
print("  def peneloux_h2o(T_K: float) -> float:")
print("      '''Temperature-dependent Péneloux volume shift for H₂O [m³/mol].'''")
print(f"      TR = T_K / _PENELOUX_H2O_TC")
print(f"      c_cm3_mol = float(np.polyval(_PENELOUX_H2O_COEFFS, TR))")
print(f"      return c_cm3_mol * 1e-6   # cm³/mol → m³/mol")

# Also print all-degrees comparison
print("\n  All-degrees comparison:")
print(f"  {'Deg':>4}  {'IAPWS-95 AARE':>15}  {'Exp AARE':>10}  {'#coeff':>7}")
for deg, res in poly_results.items():
    exp_aare_str = "N/A"
    if len(df_exp) > 0:
        c_poly_exp = np.polyval(res['coeffs'], TR_exp)
        rho_poly_exp = M_H2O_g * 1000.0 / (df_exp['Vm_EoS'].values + c_poly_exp)
        aare_exp_v = np.mean(np.abs(rho_poly_exp - rho_ref_exp) / rho_ref_exp) * 100
        exp_aare_str = f"{aare_exp_v:.4f}%"
    print(f"  {deg:>4}  {res['aare_iapws']:>14.4f}%  {exp_aare_str:>10}  {deg+1:>7}")

# ============================================================================
# PART 6 — Diagnostic figures
# ============================================================================
print("\n" + "=" * 68)
print("Step 6: Generating figures …")
print("=" * 68)

# ── Figure 1: c_opt(T) and polynomial fits ───────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
T_C_fit = T_fit - 273.15
TR_plot = np.linspace(TR_fit.min() - 0.02, TR_fit.max() + 0.02, 300)
T_C_plot = TR_plot * Tc_water - 273.15

ax = axes[0]
ax.plot(T_C_fit, c_fit, 'ko', ms=6, zorder=5, label='Per-T optimal $c$')
colors_deg = {2: 'steelblue', 3: 'seagreen', 4: 'darkorange', 5: 'tomato', 6: 'purple'}
for deg, res in poly_results.items():
    c_line = np.polyval(res['coeffs'], TR_plot)
    ax.plot(T_C_plot, c_line, color=colors_deg[deg], lw=1.5,
            label=f'Poly deg {deg}  (AARE={res["aare_iapws"]:.3f}%)')

ax.axhline(0, color='gray', lw=0.8, ls='--')
ax.axhline(0.1105, color='gray', lw=0.8, ls=':', alpha=0.7, label='Current constant (0.1105)')
ax.set_xlabel('$T$ (°C)', fontsize=13)
ax.set_ylabel('$c$ [cm³ mol⁻¹]', fontsize=13)
ax.set_title('Optimal H₂O Péneloux shift vs temperature', fontsize=11)
ax.legend(fontsize=7, ncol=2)
ax.grid(True, ls=':', alpha=0.4)

# ── Figure 2: AARE comparison across datasets ────────────────────────────────
ax = axes[1]
# Per-T AARE: no shift, best polynomial, constant shift
T_C_arr = []
aare_noshift_arr = []
aare_bestpoly_arr = []
aare_const_arr = []
const_c = 0.1105   # current constant cm³/mol

for T in T_fit:
    sub = df_liq[df_liq['T_K'] == T]
    if sub.empty: continue
    T_C_arr.append(T - 273.15)
    rho_ref_t   = sub['rho_ref'].values
    Vm_t        = sub['Vm_EoS'].values
    rho_noshift = M_H2O_g * 1000.0 / Vm_t
    rho_const   = M_H2O_g * 1000.0 / (Vm_t + const_c)
    TR_t        = T / Tc_water
    c_best      = float(np.polyval(best_coeffs, TR_t))
    rho_best    = M_H2O_g * 1000.0 / (Vm_t + c_best)

    aare_noshift_arr.append(np.mean(np.abs(rho_noshift - rho_ref_t) / rho_ref_t) * 100)
    aare_const_arr.append  (np.mean(np.abs(rho_const   - rho_ref_t) / rho_ref_t) * 100)
    aare_bestpoly_arr.append(np.mean(np.abs(rho_best   - rho_ref_t) / rho_ref_t) * 100)

ax.plot(T_C_arr, aare_noshift_arr,  'k--', lw=1.2, label='No shift (current paper)')
ax.plot(T_C_arr, aare_const_arr,    'b--', lw=1.2, label='Constant 0.1105 cm³/mol')
ax.plot(T_C_arr, aare_bestpoly_arr, 'r-',  lw=2.0, label=f'Poly deg {best_deg} (optimised)')
ax.axhline(0.02, color='gray', ls=':', lw=0.9, label='0.02% target')
ax.set_xlabel('$T$ (°C)', fontsize=13)
ax.set_ylabel('AARE in $\\rho$ (%)', fontsize=13)
ax.set_title('Density AARE vs IAPWS-95 by temperature', fontsize=11)
ax.legend(fontsize=8)
ax.set_yscale('log')
ax.grid(True, which='both', ls=':', alpha=0.4)
ax.set_ylim(bottom=1e-4)

fig.tight_layout()
fig.savefig('figures/density/peneloux_opt_c.png', dpi=150, bbox_inches='tight')
plt.close(fig)
print("  Saved figures/density/peneloux_opt_c.png")

# ── Figure 3: Parity plots before / after ────────────────────────────────────
if len(df_exp) > 0:
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    T_exp_all = sorted(df_exp['T_K'].unique())
    cmap = plt.cm.viridis
    norm_T = plt.Normalize(vmin=min(T_exp_all) - 273.15, vmax=max(T_exp_all) - 273.15)

    c_poly_exp = np.polyval(best_coeffs, TR_exp)
    rho_poly_exp = M_H2O_g * 1000.0 / (df_exp['Vm_EoS'].values + c_poly_exp)
    rho_noshift_exp = M_H2O_g * 1000.0 / df_exp['Vm_EoS'].values
    aare_noshift_exp2 = np.mean(np.abs(rho_noshift_exp - rho_ref_exp) / rho_ref_exp) * 100
    aare_poly_exp2    = np.mean(np.abs(rho_poly_exp    - rho_ref_exp) / rho_ref_exp) * 100

    for ax, rho_pred_arr, title_suffix, aare_val in [
            (axes[0], rho_noshift_exp, 'No shift', aare_noshift_exp2),
            (axes[1], rho_poly_exp,    f'Poly deg {best_deg}', aare_poly_exp2)]:
        df_exp2 = df_exp.copy(); df_exp2['rho_pred'] = rho_pred_arr
        for T in T_exp_all:
            g = df_exp2[df_exp2['T_K'] == T]
            ax.scatter(g['rho_exp'], g['rho_pred'],
                       color=cmap(norm_T(T - 273.15)), s=50, zorder=4)
        lo = min(rho_ref_exp.min(), rho_pred_arr.min()) - 5
        hi = max(rho_ref_exp.max(), rho_pred_arr.max()) + 5
        lv = np.linspace(lo, hi, 300)
        ax.plot(lv, lv, 'k-', lw=0.8)
        ax.fill_between(lv, lv*0.999, lv*1.001, color='green',  alpha=0.20, label='±0.1%')
        ax.fill_between(lv, lv*0.990, lv*1.010, color='orange', alpha=0.12, label='±1%')
        ax.set_xlabel(r'Experimental $\rho_W$ [kg m$^{-3}$]', fontsize=11)
        ax.set_ylabel(r'eCPA $\rho_W$ [kg m$^{-3}$]', fontsize=11)
        ax.set_title(f'{title_suffix}  (AARE = {aare_val:.3f}%)', fontsize=11)
        ax.legend(fontsize=8)
        ax.set_xlim(lo, hi); ax.set_ylim(lo, hi); ax.set_aspect('equal')
        ax.grid(True, ls=':', alpha=0.35)

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm_T)
    sm.set_array([])
    fig.colorbar(sm, ax=axes, label='$T$ (°C)', shrink=0.75, pad=0.015, location='right')
    fig.suptitle('Experimental CO₂-saturated density: no-shift vs optimised Péneloux', y=1.01)
    fig.tight_layout()
    fig.savefig('figures/density/peneloux_parity.png', dpi=150, bbox_inches='tight')
    plt.close(fig)
    print("  Saved figures/density/peneloux_parity.png")

print("\nDone.")
